FROM nginx:1.27.2

RUN groupadd -r user && useradd -r -g user user
RUN chown -R user:user /usr/share/nginx/html
USER user

RUN apt-get update && apt-get -y upgrade

CMD [ "echo","-c", "echo hello =)" ]