services:
  web:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  app:
    image: danielsss/aircraft:latest
    volumes:
      - app_data:/app/data

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT=example

volumes:
  app_data:
  db_data: